/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/navigashion/stack-navigation/RootStackParamList` | `/navigashion/stack-navigation/RootStackParamList`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/navigashion/stack-navigation/StackNavigator` | `/navigashion/stack-navigation/StackNavigator`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/navigashion/tab-navigation/HomeBottomtabnavigation` | `/navigashion/tab-navigation/HomeBottomtabnavigation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/navigashion/tab-navigation/MyOrderTopTabNavigation` | `/navigashion/tab-navigation/MyOrderTopTabNavigation`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/navigashion/stack-navigation/RootStackParamList` | `/navigashion/stack-navigation/RootStackParamList`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/navigashion/stack-navigation/StackNavigator` | `/navigashion/stack-navigation/StackNavigator`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/navigashion/tab-navigation/HomeBottomtabnavigation` | `/navigashion/tab-navigation/HomeBottomtabnavigation`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/navigashion/tab-navigation/MyOrderTopTabNavigation` | `/navigashion/tab-navigation/MyOrderTopTabNavigation`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/navigashion/stack-navigation/RootStackParamList${`?${string}` | `#${string}` | ''}` | `/navigashion/stack-navigation/RootStackParamList${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/navigashion/stack-navigation/StackNavigator${`?${string}` | `#${string}` | ''}` | `/navigashion/stack-navigation/StackNavigator${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/navigashion/tab-navigation/HomeBottomtabnavigation${`?${string}` | `#${string}` | ''}` | `/navigashion/tab-navigation/HomeBottomtabnavigation${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/navigashion/tab-navigation/MyOrderTopTabNavigation${`?${string}` | `#${string}` | ''}` | `/navigashion/tab-navigation/MyOrderTopTabNavigation${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/navigashion/stack-navigation/RootStackParamList` | `/navigashion/stack-navigation/RootStackParamList`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/navigashion/stack-navigation/StackNavigator` | `/navigashion/stack-navigation/StackNavigator`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/navigashion/tab-navigation/HomeBottomtabnavigation` | `/navigashion/tab-navigation/HomeBottomtabnavigation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/navigashion/tab-navigation/MyOrderTopTabNavigation` | `/navigashion/tab-navigation/MyOrderTopTabNavigation`; params?: Router.UnknownInputParams; };
    }
  }
}
